### ISSUE TITLE
get_protection_groups() method is throwing srm_client.client.SrmClientException: Unsupported namespace "urn:internaldr0" in content of SOAP body

### ISSUE THREAD

**Issue by adityabharti** [Infinidat/infi.srm_client#3]
XML request being sent:

<soap:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <CreatePropertyCollector xmlns="urn:internaldr0">
      <_this xmlns:internalvim25="urn:internalvim25" xsi:type="internalvim25:ManagedObjectReference" type="PropertyCollector">DrPropertyCollector</_this>
    </CreatePropertyCollector>
  </soap:Body>
</soap:Envelope>

Stack Trace:

Traceback (most recent call last):
  File "tt.py", line 14, in <module>
    print i_client.get_protection_groups()
  File "/Users/aditya.bharti/workspace_srm/infi.srm_client/src/srm_client/client.py", line 270, in get_protection_groups
    with self.property_collector() as key:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/aditya.bharti/workspace_srm/infi.srm_client/src/srm_client/client.py", line 155, in property_collector
    key = self._send('CreatePropertyCollector.xml')['CreatePropertyCollectorResponse']['returnval']['#text']
  File "/Users/aditya.bharti/workspace_srm/infi.srm_client/src/srm_client/client.py", line 43, in _send
    raise SrmClientException(body['soapenv:Fault']['faultstring'])
srm_client.client.SrmClientException: Unsupported namespace "urn:internaldr0" in content of SOAP body

while parsing SOAP body
at line 2, column 2

while parsing SOAP envelope
at line 1, column 0

while parsing HTTP request before method was determined
at line 1, column 0

**Comment by aksatapathy** [comment]
Hi @adityabharti . Did you get any solution for this ? I am also trying to use this but getting the same error.

**Comment by GoggiP** [comment]
PSC has stale registrations.
